export const sampleActivityData = [
  {
    activity: "Exercise",
    avgIntensity: 7.8,
    emoji: "😊",
    label: "Happy",
    count: 12,
    dominantMood: "happy",
  },
  {
    activity: "Reading",
    avgIntensity: 6.9,
    emoji: "😌",
    label: "Content",
    count: 8,
    dominantMood: "content",
  },
  {
    activity: "Meditation",
    avgIntensity: 6.5,
    emoji: "😌",
    label: "Content",
    count: 7,
    dominantMood: "content",
  },
  {
    activity: "Socializing",
    avgIntensity: 7.2,
    emoji: "🤩",
    label: "Excited",
    count: 9,
    dominantMood: "excited",
  },
  {
    activity: "Creative Hobby",
    avgIntensity: 7.0,
    emoji: "😊",
    label: "Happy",
    count: 6,
    dominantMood: "happy",
  },
  {
    activity: "Work",
    avgIntensity: 5.2,
    emoji: "😐",
    label: "Neutral",
    count: 15,
    dominantMood: "neutral",
  },
  {
    activity: "Social Media",
    avgIntensity: 4.8,
    emoji: "😐",
    label: "Neutral",
    count: 11,
    dominantMood: "neutral",
  },
  {
    activity: "Late Night",
    avgIntensity: 4.2,
    emoji: "😴",
    label: "Tired",
    count: 8,
    dominantMood: "tired",
  },
  {
    activity: "Studying",
    avgIntensity: 5.5,
    emoji: "😐",
    label: "Neutral",
    count: 10,
    dominantMood: "neutral",
  },
  {
    activity: "Family Time",
    avgIntensity: 6.7,
    emoji: "😊",
    label: "Happy",
    count: 7,
    dominantMood: "happy",
  },
  {
    activity: "Outdoor Activities",
    avgIntensity: 7.5,
    emoji: "😊",
    label: "Happy",
    count: 5,
    dominantMood: "happy",
  },
  {
    activity: "Travel",
    avgIntensity: 7.9,
    emoji: "🤩",
    label: "Excited",
    count: 3,
    dominantMood: "excited",
  },
  {
    activity: "Entertainment",
    avgIntensity: 6.8,
    emoji: "🤩",
    label: "Excited",
    count: 6,
    dominantMood: "excited",
  },
  {
    activity: "Sports",
    avgIntensity: 7.3,
    emoji: "😊",
    label: "Happy",
    count: 4,
    dominantMood: "happy",
  },
  {
    activity: "Shopping",
    avgIntensity: 6.2,
    emoji: "🤩",
    label: "Excited",
    count: 5,
    dominantMood: "excited",
  },
]
